export const UPDATE_NUMBER_OF_LEDS = 'UPDATE_NUMBER_OF_LEDS';
export type UPDATE_NUMBER_OF_LEDS = typeof UPDATE_NUMBER_OF_LEDS;

export const UPDATE_LED_LAYOUT = 'UPDATE_LED_LAYOUT';
export type UPDATE_LED_LAYOUT = typeof UPDATE_LED_LAYOUT;

export const UPDATE_GRAPH_DETAIL_START = 'UPDATE_GRAPH_DETAIL_START';
export type UPDATE_GRAPH_DETAIL_START = typeof UPDATE_GRAPH_DETAIL_START;

export const UPDATE_GRAPH_DETAIL_END = 'UPDATE_GRAPH_DETAIL_END';
export type UPDATE_GRAPH_DETAIL_END = typeof UPDATE_GRAPH_DETAIL_END;
