export const UPDATE_NUMBER_OF_LEDS = 'UPDATE_NUMBER_OF_LEDS';
export type UPDATE_NUMBER_OF_LEDS = typeof UPDATE_NUMBER_OF_LEDS;

export const UPDATE_LED_LAYOUT = 'UPDATE_LED_LAYOUT';
export type UPDATE_LED_LAYOUT = typeof UPDATE_LED_LAYOUT;